#*******************************************************************************
#* makefile.mk
#*------------------------------------------------------------------------------
#* Makefile used to generate the Application binaries (GNU ARM format).
#* This file was automatically generated by IngeDev. Please, do not edit!
#*******************************************************************************

#-------------------------------------------------------------------------------
# General constants
#-------------------------------------------------------------------------------
EMPTY :=
SPACE := $(EMPTY) $(EMPTY)

#-------------------------------------------------------------------------------
# Project and file names
#-------------------------------------------------------------------------------
# Project name
PROJECT_NAME    := CVConnectTETRA
# Compiler version
COMPILER_VERSION    := GNU ARM 5.3.1 (HWTetra)
#path compiler
PATH_COMPILER       :=D:/Ingenico/IngeDev_8.20.26.0/toolchains/gnuArm531v7a-5/bin
# Configuration name
CFG_NAME        := GNU_ARM_DEBUG_TETRA
# Target file name (without extension)
TRG_FILE_NAME   := CVConnectTE

#-------------------------------------------------------------------------------
# Directories
#-------------------------------------------------------------------------------
# Binaries directory
BIN_DIR         := Bin
# Object directory
OBJ_DIR         := Obj
# Build files directory
BUILD_FILES_DIR := BuildFiles

#-------------------------------------------------------------------------------
# Input files path for the current configuration
#-------------------------------------------------------------------------------
# Build files path
BUILD_FILES_PATH:= $(BUILD_FILES_DIR)/$(CFG_NAME)

#-------------------------------------------------------------------------------
# Output files path for the current configuration
#-------------------------------------------------------------------------------
# Object files path
OBJ_PATH        := $(OBJ_DIR)/$(CFG_NAME)
# Binary files path
BIN_PATH        := $(BIN_DIR)/$(CFG_NAME)

#-------------------------------------------------------------------------------
# Compiler, linker, assembler, ...
#-------------------------------------------------------------------------------
# Gnu Compiler executable
CC              := arm-islero-linux-gnueabihf-gcc.exe
# Gnu Assembler executable
AS              := arm-islero-linux-gnueabihf-as.exe
# Gnu Linker executable
LD              := arm-islero-linux-gnueabihf-ld.exe
# Gnu binary file transforming executable
OBJ_COPY        := arm-islero-linux-gnueabihf-objcopy.exe
# Gnu binary sections size executable
SIZE            := arm-islero-linux-gnueabihf-size.exe
# Gnu binary Obj Dump executable
OBJ_DUMP        := arm-islero-linux-gnueabihf-objdump.exe
# Gnu binary strip executable
STRIP           := arm-islero-linux-gnueabihf-strip.exe


#-------------------------------------------------------------------------------
# Gnu Win32 tools
#-------------------------------------------------------------------------------
# Remove tool
RM              := rm.exe -fr
# Make directory tool
MKDIR           := mkdir.exe -p
# Copy tool
CP              := cp.exe
# Printf tool
PRINTF          := printf

#-------------------------------------------------------------------------------
# Includes path used in compilation process
#-------------------------------------------------------------------------------
INCLUDES_PATH   := \
-IInc \
-ID:/MyProjects/TETRA/cib_dll_t3/ExpInc \
-isystemD:/Ingenico/IngeDev_8.20.26.0/toolchains/gnuArm531v7a-5/arm-islero-linux-gnueabihf/include/c++/5.3.1 \
-isystemD:/Ingenico/IngeDev_8.20.26.0/toolchains/gnuArm531v7a-5/arm-islero-linux-gnueabihf/include/c++/5.3.1/arm-islero-linux-gnueabihf \
-isystemD:/Ingenico/IngeDev_8.20.26.0/toolchains/gnuArm531v7a-5/arm-islero-linux-gnueabihf/include/c++/5.3.1/backward \
-isystemD:/Ingenico/IngeDev_8.20.26.0/toolchains/gnuArm531v7a-5/lib/gcc/arm-islero-linux-gnueabihf/5.3.1/include \
-isystemD:/Ingenico/IngeDev_8.20.26.0/toolchains/gnuArm531v7a-5/lib/gcc/arm-islero-linux-gnueabihf/5.3.1/include-fixed \
-isystemD:/Ingenico/IngeDev_8.20.26.0/toolchains/gnuArm531v7a-5/arm-islero-linux-gnueabihf/include \
-isystemD:/Ingenico/IngeDev_8.20.26.0/toolchains/gnuArm531v7a-5/arm-islero-linux-gnueabihf/sysroot/usr/include \
-IC:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/inc/c/Platform \
-IC:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/inc/c/Platform/CommonTools \
-IC:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/inc/c/Platform/Communication \
-IC:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/inc/c/Platform/GOAL \
-IC:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/inc/c/Platform/GTL \
-IC:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/inc/c/Platform/PCL \
-IC:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/inc/c/Platform/Pinpad \
-IC:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/inc/c/Platform/SDK \
-IC:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/inc/c/Platform/SQLite \
-IC:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/inc/c/Platform/TPass \
-IC:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/inc/c/OS \
-IC:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/inc/cpp \
-IC:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/inc/cpp/google \
-IC:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/inc/cpp/ingenico \
-IC:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/proto \

#-------------------------------------------------------------------------------
# Includes path used in assembler process
#-------------------------------------------------------------------------------
INCLUDES_ASM_PATH   := \
-IInc \
-ID:/MyProjects/TETRA/cib_dll_t3/ExpInc \


#-------------------------------------------------------------------------------
# Libraries to be included during link operation
#-------------------------------------------------------------------------------
LIBS            := \
D:/MyProjects/TETRA/cib_dll_t3/Bin/GNU_ARM_DEBUG_TETRA/libCibT3Dll.so \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/LIBBATTERY.T3L \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/LIBBLIGHT.T3L \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/LIBBUZZER.T3L \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/LIBCAPTURE.T3L \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/LIBBIO.T3L \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/LIBPPADTEXT.T3L \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/LIBGPS.T3L \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/LIBDESKTOP.T3L \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/libethernet.lib \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/LIBEXPLORER.T3L \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/libgprs.lib \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/libspmci.lib \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/libpcl.lib \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/libwifi.lib \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/LIBGRAPHICS.T3L \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/LIBACCELERO.T3L \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/LIBHEADER.T3L \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/LIBINACTIVI.T3L \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/liblinklayer.lib \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/libtmscall.lib \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/libtmsdownload.lib \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/libmodem.lib \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/LIBMONITOR.T3L \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/LIBOS.T3L \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/libpackip.lib \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/LIBPRINTER.T3L \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/LIBPROTOBUF.T3L \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/LIBSCRSAVER.T3L \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/LIBSERVICE.T3L \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/libSecurity.lib \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/LIBSETTING.T3L \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/libsoftmgt.lib \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/LIBSVCDIRPX.T3L \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/LIBSVCDIRSK.T3L \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/libTrEngine.T3L \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/LIBVIRT_KB.T3L \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/libtlvtree.lib \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/SQLITELIB.a \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/LibBridge.T3L \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/libbluetooth.lib \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/LIBMORPHO.T3L \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/libndef.lib \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/LIB1LINESCR.T3L \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/LIBCASHDRAW.T3L \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform/termdiag.a \

#-------------------------------------------------------------------------------
# System libraries path to be included during link operation
#-------------------------------------------------------------------------------
SYSTEM_LIBS_PATH     := \
-LD:/Ingenico/IngeDev_8.20.26.0/toolchains/gnuArm531v7a-5/lib/gcc/arm-islero-linux-gnueabihf/5.3.1 \
-LD:/Ingenico/IngeDev_8.20.26.0/toolchains/gnuArm531v7a-5/arm-islero-linux-gnueabihf/sysroot/lib \
-LC:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform \
-LC:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/OS \




#-------------------------------------------------------------------------------
# RPATH for libraries to be included during link operation
#-------------------------------------------------------------------------------
LIBS_RPATH_LINK   := \
-rpath-link=D:/Ingenico/IngeDev_8.20.26.0/toolchains/gnuArm531v7a-5/lib/gcc/arm-islero-linux-gnueabihf/5.3.1 \
-rpath-link=D:/Ingenico/IngeDev_8.20.26.0/toolchains/gnuArm531v7a-5/arm-islero-linux-gnueabihf/sysroot/lib \
-rpath-link=C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/OS \
-rpath-link=C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib_for_dbg \
-rpath-link=D:/MyProjects/TETRA/cib_dll_t3/Bin/GNU_ARM_DEBUG_TETRA \
-rpath-link=C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/Platform \
-rpath-link=C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/lib/OS \


#-------------------------------------------------------------------------------
# Package libraries to be included during link operation
#-------------------------------------------------------------------------------
PACKAGE_LIBS    :=\
-lGRAPHICLIB \
-lchip \
-lcless \
-lgtl \
-lled \
-lPpad \
-lswipe \
-ltransac \
-lOSLAYER \
-ltelinux \
-ltoken \
-ltmsapplication \
-lmifare \
-lmifareProxy \
-lhbeat \
-lautoinit \
-lcommmisc \

#-------------------------------------------------------------------------------
# System libraries to be included during link operation
#-------------------------------------------------------------------------------
SYS_LIBS     :=\
-lc \
-lgcc \
-lgcc_s \
-lstdc++ \

#-------------------------------------------------------------------------------
# System libraries to be included during link operation
#-------------------------------------------------------------------------------
SYSTEM_LIBS     :=\
	$(PACKAGE_LIBS)\
	$(SYS_LIBS)


#-------------------------------------------------------------------------------
# Result output files
#-------------------------------------------------------------------------------
# Binary file
BINARY_FILE     := $(BIN_PATH)/$(TRG_FILE_NAME).BIN
BINARY_FILE_NO_STRIP     := $(OBJ_PATH)/$(TRG_FILE_NAME).T3A

#-------------------------------------------------------------------------------
# Result Listing files
#-------------------------------------------------------------------------------
# Binary file
LST_FILE     := $(OBJ_PATH)/$(TRG_FILE_NAME).lst

#-------------------------------------------------------------------------------
# Intermediate files
#-------------------------------------------------------------------------------
# Result map file location
INTER_MAP_FILE  := $(OBJ_PATH)/$(TRG_FILE_NAME).map
# AXF file location
INTER_AXF_FILE  := $(OBJ_PATH)/$(TRG_FILE_NAME).axf
# SIZE file location
INTER_SIZE_FILE  := $(OBJ_PATH)/$(TRG_FILE_NAME).siz
#Includes opt file
INCLUDE_FILE_OPT:= $(OBJ_PATH)/includesFiles.opt
#Linker opt file
LD_OPT_FILE:=$(OBJ_PATH)/ldFile.opt

#-------------------------------------------------------------------------------
# Default compiler, linker, assembler options
#-------------------------------------------------------------------------------
# Default compiler options
CC_DEF_OPTS     := -g -c -Wall -fPIE
# Default assembler options
AS_DEF_OPTS     := 
# Default linker options
LD_DEF_OPTS     := -pie -z noexecstack --copy-dt-needed-entries --as-needed -I/lib/ld-linux.so.3 --exclude-libs ALL --allow-shlib-undefined --sysroot=D:/Ingenico/IngeDev_8.20.26.0/toolchains/gnuArm531v7a-5/arm-islero-linux-gnueabihf/sysroot -Map=$(INTER_MAP_FILE)
# Default linker options
OD_DEF_OPTS     := --disassemble --source --syms

#-------------------------------------------------------------------------------
# Specific compiler, linker, assembler options
#-------------------------------------------------------------------------------
# Specific compiler options
CC_SPEC_OPTS    := -mthumb -fstack-protector-strong  -D_ING_GNU_ARM_DEBUG_TETRA
CC_SPEC_OPTS    +=  -D__FRAMEWORK_TELIUM_3__=1 -D_PACKAGE_NAME_=Telium3SDK -DSDK_VERSION=112003 -D__TELIUM3__=1
CC_SPEC_OPTS    +=  -D_ING_TELIUM_SDK_LOC='"C:\Program Files\TeliumSDK\SDK11.20.3.05"' -D_ING_TELIUM_SDK_NAME='"Telium SDK"' -D_ING_TELIUM_SDK_VERSION='"11.20.3.05"' -D_ING_APPLI_BINARY_NAME='"CVConnectTE"' -D_ING_APPLI_FAMILY='"8217869"' -D_ING_APPLI_TYPE=0x6e -D_ING_APPLI_TELIUM_TETRA_FULL_BINARY_NAME='"CVConnectTE.T3A"' -D_ING_APPLI_TELIUM_COMPATIBILITY='"Telium Tetra"' -D_ING_APPLI_SIGN_MODE='"Unsigned"' -D_ING_APPLI_DATA_FILE_TELIUM_TETRA_BINARY_NAME='"DATA006E250.T3P"' -D_ING_APPLI_TELIUM_TETRA_PACKAGE_NAME='"2500000110000000_CVConnectTETRA.P3A"' -D_ING_APPLI_TELIUM_TETRA_PACKAGE_TYPE='"A"' -D_ING_APPLI_TELIUM_TETRA_PACKAGE_RANGE='"00"' -D_ING_APPLI_TELIUM_TETRA_PACKAGE_COUNTRY_CODE='"250"' -D_ING_APPLI_TELIUM_TETRA_PACKAGE_IDENTIFIER='"110"' -D_ING_APPLI_TELIUM_TETRA_PACKAGE_VERSION='"000000"' -D_ING_APPLI_TELIUM_TETRA_COMPONENT_NAME='"CVConnectTE.T3A"' -D_ING_APPLI_TELIUM_TETRA_PACKAGE_FAMILY='"CVConnectTETRA"' -D_ING_APPLI_TELIUM_TETRA_PACKAGE_ROOTNAME='"2500000110000000_CVConnectTETRA"' -D_ING_APPLI_CURRENT_CONFIG_NAME='"GNU_ARM_DEBUG_TETRA"' -D_ING_APPLI_FULL_BINARY_NAME='"CVConnectTE.T3A"'
# Specific assembler options
AS_SPEC_OPTS    := -mthumb  --defsym _ING_GNU_ARM_DEBUG_TETRA=1
AS_SPEC_OPTS    +=  $(INCLUDES_ASM_PATH)
# Specific linker options
LD_SPEC_OPTS    := 
# Specific strip options
ST_SPEC_OPTS    :=  --remove-section=.comment 

#-------------------------------------------------------------------------------
# Compiler, linker, assembler options
# default + specific options
#-------------------------------------------------------------------------------
# Compiler options
CC_OPTS         := $(CC_DEF_OPTS) $(CC_SPEC_OPTS)
# Assembler options
AS_OPTS         := $(AS_DEF_OPTS) $(AS_SPEC_OPTS)
# Linker options
LD_OPTS         := $(LD_DEF_OPTS) $(LD_SPEC_OPTS)
#ObjDump options
OD_OPTS         := $(OD_DEF_OPTS)
#Strip options
ST_OPTS         := $(ST_SPEC_OPTS)

#-------------------------------------------------------------------------------
# SRC_OBJS is the list of the project object files
#-------------------------------------------------------------------------------
SRC_OBJS        := \
$(OBJ_PATH)/Main.o \
$(OBJ_PATH)/BaseDrawWindow.o \
$(OBJ_PATH)/TxnStartEnd.o \
$(OBJ_PATH)/Utils.o \
$(OBJ_PATH)/Transaction.o \
$(OBJ_PATH)/CvConnect.o \

#-------------------------------------------------------------------------------
# Dependencies
#-------------------------------------------------------------------------------
DEPENDENCIES    := \
$(BUILD_FILES_PATH)/makefile.mk

#===============================================================================
# Rule to make the project
#===============================================================================
#-------------------------------------------------------------------------------
# Rule for the binary files generation
#-------------------------------------------------------------------------------
$(BINARY_FILE): $(INTER_SIZE_FILE) \

	$(OBJ_COPY) -O elf32-littlearm $(INTER_AXF_FILE) $@
	@echo "duplicate bin file :  $@ to $(BINARY_FILE_NO_STRIP)"
	$(CP) $@ $(BINARY_FILE_NO_STRIP)
	@echo "Stripping terminal binary file: "
	$(STRIP) $(ST_OPTS) $@
	@echo "'$@' binary file generated."

#===============================================================================
# Rule for startup files rules generation
#===============================================================================
START_OBJS:= D:/Ingenico/IngeDev_8.20.26.0/toolchains/gnuArm531v7a-5/arm-islero-linux-gnueabihf/sysroot/usr/lib/crti.o \
D:/Ingenico/IngeDev_8.20.26.0/toolchains/gnuArm531v7a-5/arm-islero-linux-gnueabihf/sysroot/usr/lib/crt1.o \
D:/Ingenico/IngeDev_8.20.26.0/toolchains/gnuArm531v7a-5/lib/gcc/arm-islero-linux-gnueabihf/5.3.1/crtbegin.o \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/startfiles/startup_t3entry.o \

END_OBJS:= D:/Ingenico/IngeDev_8.20.26.0/toolchains/gnuArm531v7a-5/lib/gcc/arm-islero-linux-gnueabihf/5.3.1/crtend.o \
D:/Ingenico/IngeDev_8.20.26.0/toolchains/gnuArm531v7a-5/arm-islero-linux-gnueabihf/sysroot/usr/lib/crtn.o \
C:/Program\ Files/TeliumSDK/SDK11.20.3.05/SDKT3/HW_TETRA/gnu_531/startfiles/stapp_legacyexitpoint.o \


#-------------------------------------------------------------------------------
# Rule for includes @option file
#-------------------------------------------------------------------------------
$(INCLUDE_FILE_OPT):  $(DEPENDENCIES) | createObjDir
	@echo "Includes file list @option generation: "
	$(file >$@)
	@$(foreach Elt,$(subst \ ,|, $(INCLUDES_PATH)),$(file >>$@,"$(subst |,\ ,$(Elt))"))
	@echo "'Finished building: $@'"
	@echo ""
#===============================================================================
# Rule for linker opt files rules generation
#===============================================================================
$(LD_OPT_FILE):  $(DEPENDENCIES) $(SRC_OBJS)  $(LIBS) \
	$(START_OBJS) $(END_OBJS)

	@echo ""
	@echo "Linker file @option generation"
	@$(file >$@)
	@$(foreach Elt, $(subst \ ,|,\
	$(START_OBJS) \
	$(SYSTEM_LIBS_PATH) \
	$(LIBS_RPATH_LINK) \
	$(SRC_OBJS) \
	--start-group $(LIBS) $(SYSTEM_LIBS) --end-group \
	$(END_OBJS)\
	),\
	$(file >>$@,"$(subst |,\ ,$(Elt))"))
	@echo "'Finished building: $@'"
	@echo ""

#-------------------------------------------------------------------------------
# Rule for the axf file generation
#-------------------------------------------------------------------------------
$(INTER_AXF_FILE): $(LD_OPT_FILE) \
	$(SRC_OBJS)

	@echo "'$@' link in progress..."
	$(LD) $(LD_OPTS)  -o $@ \
	@$(LD_OPT_FILE)

	@echo "'Finished building: $@'"
	@echo ""

#-------------------------------------------------------------------------------
# Rule for the elf file generation
#-------------------------------------------------------------------------------
$(INTER_SIZE_FILE): $(INTER_AXF_FILE)
	@echo "'Invoking: GNUARM Print Size'"
	$(SIZE) -A $< > $@
	@echo "'Finished building: $@'"
	@echo ""

#===============================================================================
# Rule for the .lst Generation
#===============================================================================
$(LST_FILE): $(INTER_AXF_FILE)
	$(OBJ_DUMP) $(OD_OPTS) $<  > $@
	@echo "'$@' lst file generated."

#===============================================================================
# Rule for the compilation process
#===============================================================================
ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Main.d
endif
$(OBJ_PATH)/Main.o: Src/Main.cpp $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Main.cpp' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Main.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/BaseDrawWindow.d
endif
$(OBJ_PATH)/BaseDrawWindow.o: Src/BaseDrawWindow.cpp $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/BaseDrawWindow.cpp' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/BaseDrawWindow.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/TxnStartEnd.d
endif
$(OBJ_PATH)/TxnStartEnd.o: Src/TxnStartEnd.cpp $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/TxnStartEnd.cpp' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/TxnStartEnd.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Utils.d
endif
$(OBJ_PATH)/Utils.o: Src/Utils.cpp $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Utils.cpp' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Utils.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Transaction.d
endif
$(OBJ_PATH)/Transaction.o: Src/Transaction.cpp $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Transaction.cpp' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Transaction.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/CvConnect.d
endif
$(OBJ_PATH)/CvConnect.o: Src/CvConnect.cpp $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/CvConnect.cpp' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/CvConnect.o)
	@echo "done!"
endif


#===============================================================================
# Rule for project name and configuration name display
#===============================================================================
.PHONY: displayInfo
displayInfo:
	@echo "                                     *-*-*"
	@echo "--- Project '$(PROJECT_NAME)', Configuration '$(CFG_NAME)', Compiler '$(COMPILER_VERSION)' ---"

#===============================================================================
# Rule for build target progress info display
#===============================================================================
.PHONY: displayBuildInProgress
displayBuildInProgress:
	@echo "Build in progress..."

#===============================================================================
# Rule for output directories creation
#===============================================================================
createObjDir: | $(OBJ_PATH)

$(OBJ_PATH):
	@$(MKDIR) "$(OBJ_PATH)"

createBinDir: | $(BIN_PATH)

$(BIN_PATH):
	@$(MKDIR) "$(BIN_PATH)"

#===============================================================================
# Make build rule
#===============================================================================
.PHONY: build
build: displayInfo displayBuildInProgress createObjDir createBinDir $(BINARY_FILE)
	@echo "done!"
